services:
  sign-speak-app:
    container_name: sign-speak
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.10.7
    volumes:
      - .:/app
    environment:
      - DISPLAY=$DISPLAY
      - MODE=api
    stdin_open: true
    tty: true
